### ISSUE TITLE
freenet help

### ISSUE THREAD

**Issue by thisguy0417** [freenet/fred#365]
PLEASE HELP FREENET ISSUES
i opened this account to seek help with apparently, EVERY aspect  of FREENET.
!ST off, why is there no easy to reach REAL, useful, help and
support for CORRECTLY  setting  up, and CORRECTLY  configuring, for maximum preformance,and useability OF FREENET

2ND, im browsing with 40-60 peers accessing my FREENET node, but all of a sudden, i get a screen saying FREENET is startingup or shutting down, when i didnt do anything to stop it, if it was started, it shouldnt stop unless I,(ME) stops it,
 i have it set up to start at my computers startup, so theres no reason for it to startup again unless, I,(ME), stops it. 

3RD, when i can stay "on" long enough to dl a file, i generally get an error of some kind, saying either; certain files are corrupted, to delete them /or save and restore them, or, i get internal java lang heapspace error/ but the worst one is, i have a file complete but i get a ; "java.io.EOFException",  for 99% of what i have "successfully downloaded" , not too successful,  huh,  All of what i have tried to dl has been less than 1.16 gib, tried fetching them every way possible but i almost always get the above issues.

4TH,  i am doing this on brand new, 500gb 7200 rpm hdd, 4 g ram, 60mbps up, and download wifi speed, (my computer reads 72mbps for that), freenet detects 59mbps for my up and dl speeds, no data limit, no bandwidth limit, i have dedicated 100 gib of space for the datastore, and 20gb each, for the 3 other stores,   i have my ram cache, (instead of the 43mib it wants to give me), i set it up to 240 mib. i have my os, FREENET, java, 7zip, chrome, adobe flash player and vlc player, i also have 1 3rd party system cleaning program and one ram boost program. my os and all its files are on a partition with mozilla, and the booster and cleaner, with 226 of 248 gb freespace, the rest is on its own partition with 98 of 217 gb freespace, i have also done the things to speed up and hold mem longer and this and that for mozilla firefox but nothing works, so i should, by rights, have plenty of space and speed for this program

i can almost always get to where i want to go, but when i start trying to dl stuff, all hell breaks loose, ive been trying this for a month now and i may have successfully downloaded 3-4 working files, but with all the crap that keeps hapening, i loose it, please help, even if this isnt the right page for help,

i really like where i can go here in the FREENET, and would like to become a valued participant, maybe even a donor, but, if it dont work, im not going to waste my time and money, ive already put in 200 hours of pretty much unsuccessful effort, and maybe, if im lucky, 10-15 successful hours in, please even if this is not  the right place, if you can, forward this to someone that can help, im giving my permission to do so, or point me in the right direction for REAL HELP AND SUPPORT FOR FREENET, google is removing info from the web to assist with freenet, i couldnt find any useful help on tor either, if therer is info out there its either old or removed,crossed off on google, hopefully,  its worth saying this , but i doubt it,cuz i havent had any luck finding real help yet, but im going to say, thank you in advance for taking the time to read this and for any future associations

                                                                     sincerely thisguy0417

**Comment by bertm** [comment]
The [Freenet Project website](https://freenetproject.org/) lists multiple options to get help, including a [FAQ](https://freenetproject.org/faq.html), several [mailing lists](https://freenetproject.org/lists.html) and [IRC chat](https://freenetproject.org/irc.html). A [setup guide](http://freesocial.draketo.de/) is linked to aid with the installation and first-time use of Freenet.

To get support for the problems you encounter, I suggest you send a message to the [support mailing list](https://emu.freenetproject.org/cgi-bin/mailman/listinfo/support/), briefly explaining the problems you encounter. (please first subscribe to this list before sending a message to it, otherwise your messages will have to be manually approved before anyone can reply to them)

As a general thought on your problems stated so far: the apparent performance of your node is heavily influenced by the actual performance of the nodes you are connected to. Increasing memory and disk space allocations do not necessarily make your node work any faster or better. Your involuntary node restarts can easily be caused by a misguided configuration. If you don't know what you are doing, leave the "advanced mode" settings to their default values, and only change the settings available in "simple mode".

Please note that this issue tracker is not used. I suggest this issue is closed, and the discussion be continued on the support mailing list.

**Comment by Thynix** [comment]
This support request has moved to [this mailing list thread](https://emu.freenetproject.org/pipermail/support/2015-May/005401.html).
